# Generated by Django 5.0.6 on 2024-06-25 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('ItemNo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Property', models.CharField(max_length=10)),
                ('Unit', models.CharField(max_length=10)),
                ('ItemDescription', models.CharField(max_length=50)),
                ('Quantity', models.CharField(max_length=10)),
                ('UnitCost', models.CharField(max_length=10)),
                ('TotalCost', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionIssueSlip',
            fields=[
                ('RISNo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ResCenterCode', models.CharField(max_length=10)),
                ('Division', models.CharField(max_length=50)),
                ('Office', models.CharField(max_length=50)),
                ('IsStockAvailable', models.CharField(max_length=10)),
                ('Quantity', models.CharField(max_length=10)),
                ('Remarks', models.CharField(max_length=100)),
                ('Purpose', models.CharField(max_length=100)),
                ('RequestedBy', models.CharField(max_length=10)),
                ('ApprovedBy', models.CharField(max_length=10)),
                ('IssuedBy', models.CharField(max_length=10)),
                ('RecievedBy', models.CharField(max_length=10)),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('SupplierNo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('SupplierName', models.CharField(max_length=50)),
                ('Tin', models.CharField(max_length=30)),
                ('DateCreated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('PONo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('SupplierNo', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=100)),
                ('PlaceOfDelivery', models.CharField(max_length=100)),
                ('DateOfDelivery', models.DateTimeField()),
                ('DeliveryTerm', models.CharField(max_length=100)),
                ('FundCluster', models.CharField(max_length=10)),
                ('FundsAvailable', models.CharField(max_length=10)),
                ('ORSBURSNo', models.CharField(max_length=10)),
                ('DateOfORSBURS', models.DateTimeField()),
                ('TotalAmount', models.CharField(max_length=10)),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
                ('ItemNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionAcceptanceReport',
            fields=[
                ('IARNo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('RequisitioningOffice', models.CharField(max_length=50)),
                ('ResCenterCode', models.CharField(max_length=10)),
                ('InvoiceNo', models.CharField(max_length=10)),
                ('DateInspected', models.DateTimeField()),
                ('DateReceived', models.DateTimeField()),
                ('IsInspectedAndVerified', models.CharField(max_length=10)),
                ('IsComplete', models.CharField(max_length=10)),
                ('IsPartial', models.CharField(max_length=10)),
                ('DateCreated', models.DateTimeField()),
                ('ItemNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item')),
                ('PONo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.purchaseorder')),
                ('SupplierNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('PRNo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ResCenterCode', models.CharField(max_length=10)),
                ('Purpose', models.CharField(max_length=50)),
                ('RequestedBy', models.CharField(max_length=50)),
                ('ApprovedBy', models.CharField(max_length=50)),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
                ('ItemNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
