# Generated by Django 5.0.6 on 2024-06-26 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspectionacceptancereport',
            old_name='ItemNo',
            new_name='Item',
        ),
        migrations.RenameField(
            model_name='inspectionacceptancereport',
            old_name='PONo',
            new_name='PurchaseOrder',
        ),
        migrations.RenameField(
            model_name='inspectionacceptancereport',
            old_name='SupplierNo',
            new_name='Supplier',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='ItemNo',
            new_name='Item',
        ),
        migrations.RenameField(
            model_name='purchaserequest',
            old_name='username',
            new_name='User',
        ),
        migrations.AddField(
            model_name='requisitionissueslip',
            name='Item',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='api.item'),
            preserve_default=False,
        ),
    ]
