# Generated by Django 5.0.6 on 2024-06-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_datecreated_inspectionacceptancereport_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='TotalCost',
            field=models.CharField(default=123, max_length=10),
            preserve_default=False,
        ),
    ]
