# Generated by Django 5.0.6 on 2024-06-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_item_totalcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionacceptancereport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
